const STORAGE="mandwa_bhaira_bhai_people_v3",OLD1="mandwa_bhaira_bhai_people_v2",OLD2="mandwa_bhaira_bhai_people_v1",FINE=30,$=id=>document.getElementById(id);
let people=JSON.parse(localStorage.getItem(STORAGE)||"null");
if(!Array.isArray(people)){let old=JSON.parse(localStorage.getItem(OLD1)||localStorage.getItem(OLD2)||"[]")||[];people=old.map(p=>({...p,records:p.records||{}}))}
const esc=x=>String(x??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const key=()=>`${$("month").value}-${$("meeting").value}`;
const rec=(p,k)=>p.records?.[k];
function save(){localStorage.setItem(STORAGE,JSON.stringify(people));render()}
function calcAge(d){if(!d)return"";let b=new Date(d),t=new Date(),a=t.getFullYear()-b.getFullYear(),m=t.getMonth()-b.getMonth();if(m<0||(m===0&&t.getDate()<b.getDate()))a--;return a>=0?a:""}
function setFormFine(){$("formFine").textContent=$("attendance").value==="absent"?"₹30":"₹0"}
$("dob").onchange=()=>{let a=calcAge($("dob").value);if(a!=="")$("age").value=a};
$("attendance").onchange=setFormFine;
$("month").onchange=()=>{resetForm();render()};$("meeting").onchange=()=>{resetForm();render()};
$("personForm").onsubmit=e=>{e.preventDefault();let id=$("editId").value,k=key(),d={serial:+$("serial").value,name:$("name").value.trim(),father:$("father").value.trim(),dob:$("dob").value,age:$("age").value,house:$("house").value},a=$("attendance").value;if(!d.serial||!d.name)return alert("क्रमांक और नाम भरना जरूरी है");
let p=id?people.find(x=>x.id===id):people.find(x=>x.serial===d.serial);if(!p){p={id:crypto.randomUUID(),...d,records:{}};people.push(p)}else Object.assign(p,d);p.records=p.records||{};p.records[k]={attendance:a,fine:a==="absent"?FINE:0};people.sort((x,y)=>x.serial-y.serial);save();resetForm()};
function resetForm(){$("personForm").reset();$("editId").value="";$("saveBtn").textContent="＋ व्यक्ति जोड़ें";$("attendance").value="present";setFormFine()}
function monthFine(m){return people.reduce((s,p)=>s+[1,2].reduce((x,n)=>x+(rec(p,`${m}-${n}`)?.attendance==="absent"?FINE:0),0),0)}
function allFine(){return people.reduce((s,p)=>s+Object.values(p.records||{}).filter(r=>r.attendance==="absent").length*FINE,0)}
function render(){let q=$("search").value.toLowerCase(),k=key(),arr=people.filter(p=>String(p.serial).includes(q)||p.name.toLowerCase().includes(q)||p.father.toLowerCase().includes(q)||String(p.house||"").toLowerCase().includes(q));$("peopleTable").innerHTML=arr.map(p=>{let r=rec(p,k),a=r?.attendance,f=a==="absent"?FINE:0;return `<tr><td>${esc(p.serial)}</td><td><b>${esc(p.name)}</b></td><td>${esc(p.father)}</td><td>${esc(p.dob)}</td><td>${esc(p.age)}</td><td>${esc(p.house)}</td><td><span class="badge ${a==="present"?"present":a==="absent"?"absent":"unset"}">${a==="present"?"उपस्थित":a==="absent"?"अनुपस्थित":"हाजिरी नहीं"}</span></td><td class="fine-cell">₹${f}</td><td><button class="small edit" onclick="editPerson('${p.id}')">✏️ Edit</button> <button class="small delete" onclick="deletePerson('${p.id}')">🗑️</button></td></tr>`}).join("");$("emptyState").style.display=arr.length?"none":"block";let rs=people.map(p=>rec(p,k)).filter(Boolean),ab=rs.filter(r=>r.attendance==="absent").length;$("total").textContent=people.length;$("present").textContent=rs.filter(r=>r.attendance==="present").length;$("absent").textContent=ab;$("meetingFine").textContent="₹"+ab*FINE;$("monthFine").textContent="₹"+monthFine($("month").value);$("allFine").textContent="₹"+allFine();$("meetingText").textContent=`${$("month").value} • बैठक ${$("meeting").value} • अनुपस्थिति ₹30`;renderMonthly()}
function renderMonthly(){let m=$("month").value,total=0;$("monthlyTable").innerHTML=people.map(p=>{let a=rec(p,`${m}-1`),b=rec(p,`${m}-2`),x=a?.attendance==="absent"?FINE:0,y=b?.attendance==="absent"?FINE:0;total+=x+y;return `<tr><td>${esc(p.serial)}</td><td>${esc(p.name)}</td><td>${a?(a.attendance==="absent"?"अनुपस्थित ₹30":"उपस्थित ₹0"):"—"}</td><td>${b?(b.attendance==="absent"?"अनुपस्थित ₹30":"उपस्थित ₹0"):"—"}</td><td class="fine-cell">₹${x+y}</td></tr>`}).join("");$("monthlyTotal").textContent="कुल: ₹"+total}
window.editPerson=id=>{let p=people.find(x=>x.id===id),r=rec(p,key());$("editId").value=id;$("serial").value=p.serial;$("name").value=p.name;$("father").value=p.father;$("dob").value=p.dob;$("age").value=p.age;$("house").value=p.house;$("attendance").value=r?.attendance||"present";$("saveBtn").textContent="💾 इस बैठक की जानकारी अपडेट करें";setFormFine();scrollTo({top:0,behavior:"smooth"})};
window.deletePerson=id=>{let p=people.find(x=>x.id===id);if(confirm(`क्या ${p.name} का पूरा रिकॉर्ड हटाना है?`)){people=people.filter(x=>x.id!==id);save()}};
$("resetBtn").onclick=resetForm;$("search").oninput=render;
$("clearMeetingBtn").onclick=()=>{if(confirm("चुनी हुई बैठक की हाजिरी और जुर्माना हटाएँ?")){let k=key();people.forEach(p=>{if(p.records)delete p.records[k]});save()}};
$("exportBtn").onclick=()=>{let m=$("month").value,n=$("meeting").value,k=key(),rows=[["क्रमांक","नाम","पिता का नाम","जन्मतिथि","उम्र","बैठक का घर","महीना","बैठक","हाजिरी","जुर्माना"]];people.forEach(p=>{let r=rec(p,k);rows.push([p.serial,p.name,p.father,p.dob,p.age,p.house,m,`बैठक ${n}`,r?.attendance==="absent"?"अनुपस्थित":r?.attendance==="present"?"उपस्थित":"हाजिरी नहीं",r?.attendance==="absent"?FINE:0])});let csv="\ufeff"+rows.map(r=>r.map(v=>`"${String(v??"").replace(/"/g,'""')}"`).join(",")).join("\n"),u=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"})),a=document.createElement("a");a.href=u;a.download=`mandwa-${m}-meeting-${n}.csv`;a.click();URL.revokeObjectURL(u)};
$("themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("theme",document.body.classList.contains("dark")?"dark":"light");$("themeBtn").textContent=document.body.classList.contains("dark")?"☀":"☾"};
let now=new Date();$("month").value=`${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,"0")}`;if(localStorage.getItem("theme")==="dark"){document.body.classList.add("dark");$("themeBtn").textContent="☀"}setFormFine();render();